import type { TrackAudioSourceType, TrackGenre } from "@/lib/tracks"

export interface CuratedSongSeed {
  id: string
  name: string
  artists: string
  genre: TrackGenre
  videoId: string
  sourceType: TrackAudioSourceType
  lyricsSnippets: string[]
}

export const CURATED_SONG_SEEDS: CuratedSongSeed[] = [
  {
    id: "usuk-blinding-lights",
    name: "Blinding Lights",
    artists: "The Weeknd",
    genre: "usuk",
    videoId: "fHI8X4OXluQ",
    sourceType: "official_audio",
    lyricsSnippets: ["A city night keeps a lonely heart awake under bright signs."],
  },
  {
    id: "usuk-shape-of-you",
    name: "Shape of You",
    artists: "Ed Sheeran",
    genre: "usuk",
    videoId: "JGwWNGJdvx8",
    sourceType: "music_video",
    lyricsSnippets: ["A dance floor meeting turns into a playful love story."],
  },
  {
    id: "usuk-hello",
    name: "Hello",
    artists: "Adele",
    genre: "usuk",
    videoId: "T1tl66trXTQ",
    sourceType: "official_audio",
    lyricsSnippets: ["An old call carries regret across a long quiet distance."],
  },
  {
    id: "usuk-bad-guy",
    name: "bad guy",
    artists: "Billie Eilish",
    genre: "usuk",
    videoId: "4-TbQnONe_w",
    sourceType: "lyric_video",
    lyricsSnippets: ["A whispery character plays with danger and a crooked smile."],
  },
  {
    id: "usuk-blank-space",
    name: "Blank Space",
    artists: "Taylor Swift",
    genre: "usuk",
    videoId: "e-ORhEE9VVg",
    sourceType: "music_video",
    lyricsSnippets: ["A glamorous romance turns messy inside a sharp pop diary."],
  },
  {
    id: "usuk-levitating",
    name: "Levitating",
    artists: "Dua Lipa",
    genre: "usuk",
    videoId: "WHuBW3qKm9g",
    sourceType: "lyric_video",
    lyricsSnippets: ["A disco sky lifts two people above the ordinary night."],
  },
  {
    id: "usuk-as-it-was",
    name: "As It Was",
    artists: "Harry Styles",
    genre: "usuk",
    videoId: "V1Z586zoeeE",
    sourceType: "official_audio",
    lyricsSnippets: ["A bright pop memory keeps circling around change and distance."],
  },
  {
    id: "usuk-uptown-funk",
    name: "Uptown Funk",
    artists: "Mark Ronson, Bruno Mars",
    genre: "usuk",
    videoId: "7Ya2U8XN_Zw",
    sourceType: "official_audio",
    lyricsSnippets: ["A sharp funk groove walks into the room with full confidence."],
  },
  {
    id: "usuk-believer",
    name: "Believer",
    artists: "Imagine Dragons",
    genre: "usuk",
    videoId: "IhP3J0j9JmY",
    sourceType: "official_audio",
    lyricsSnippets: ["Pain turns into a loud arena-sized source of power."],
  },
  {
    id: "usuk-roar",
    name: "Roar",
    artists: "Katy Perry",
    genre: "usuk",
    videoId: "mwL1cohnHNE",
    sourceType: "lyric_video",
    lyricsSnippets: ["A quiet voice becomes brave and impossible to ignore."],
  },
  {
    id: "usuk-someone-like-you",
    name: "Someone Like You",
    artists: "Adele",
    genre: "usuk",
    videoId: "22c3_LoIfZQ",
    sourceType: "official_audio",
    lyricsSnippets: ["A past love is remembered with restraint and a heavy heart."],
  },
  {
    id: "usuk-sunflower",
    name: "Sunflower",
    artists: "Post Malone, Swae Lee",
    genre: "usuk",
    videoId: "ApXoWvfEYVU",
    sourceType: "music_video",
    lyricsSnippets: ["A warm hook floats over a sweet but unstable relationship."],
  },
  {
    id: "vpop-hay-trao-cho-anh",
    name: "Hay Trao Cho Anh",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "G8IlfFMt3so",
    sourceType: "lyric_video",
    lyricsSnippets: ["A tropical crush asks for attention with glossy summer confidence."],
  },
  {
    id: "vpop-see-tinh",
    name: "See Tinh",
    artists: "Hoang Thuy Linh",
    genre: "vpop",
    videoId: "UfMEtjxzpBk",
    sourceType: "official_audio",
    lyricsSnippets: ["A bright folk-pop flirt spins around a playful heartbeat."],
  },
  {
    id: "vpop-nang-tho",
    name: "Nang Tho",
    artists: "Hoang Dung",
    genre: "vpop",
    videoId: "0SJAzTGh1SE",
    sourceType: "official_audio",
    lyricsSnippets: ["A soft memory paints someone gentle like a poem in sunlight."],
  },
  {
    id: "vpop-co-chac-yeu-la-day",
    name: "Co Chac Yeu La Day",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "6t-MjBazs3o",
    sourceType: "music_video",
    lyricsSnippets: ["A sweet question turns a crush into a colorful confession."],
  },
  {
    id: "vpop-buoc-qua-nhau",
    name: "Buoc Qua Nhau",
    artists: "Vu",
    genre: "vpop",
    videoId: "ixdSsW5n2rI",
    sourceType: "music_video",
    lyricsSnippets: ["Two people pass each other while the city keeps moving."],
  },
  {
    id: "vpop-de-vuong",
    name: "De Vuong",
    artists: "Dinh Dung",
    genre: "vpop",
    videoId: "qkPgUgkQE4Y",
    sourceType: "music_video",
    lyricsSnippets: ["A dramatic heart holds on after love becomes unfinished."],
  },
  {
    id: "vpop-noi-nay-co-anh",
    name: "Noi Nay Co Anh",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "FN7ALfpGxiI",
    sourceType: "music_video",
    lyricsSnippets: ["A gentle promise turns love into a soft place to return to."],
  },
  {
    id: "vpop-lac-troi",
    name: "Lac Troi",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "WQU8avEv6CQ",
    sourceType: "lyric_video",
    lyricsSnippets: ["An ancient-styled heartbreak drifts through a cold lonely world."],
  },
  {
    id: "vpop-co-em-cho",
    name: "Co Em Cho",
    artists: "MIN, Mr A",
    genre: "vpop",
    videoId: "PqS2YDItY3Y",
    sourceType: "lyric_video",
    lyricsSnippets: ["A patient love waits through ordinary days and small hopes."],
  },
  {
    id: "vpop-sau-tat-ca",
    name: "Sau Tat Ca",
    artists: "ERIK",
    genre: "vpop",
    videoId: "XaXiLdlgMo0",
    sourceType: "official_audio",
    lyricsSnippets: ["After every mistake, love still wants to come back home."],
  },
  {
    id: "vpop-anh-nha-o-dau-the",
    name: "Anh Nha O Dau The",
    artists: "AMEE, B Ray",
    genre: "vpop",
    videoId: "aMW2Yf7PxM4",
    sourceType: "official_audio",
    lyricsSnippets: ["A playful crush asks one simple question again and again."],
  },
  {
    id: "vpop-co-chang-trai-viet-len-cay",
    name: "Co Chang Trai Viet Len Cay",
    artists: "Phan Manh Quynh",
    genre: "vpop",
    videoId: "EUEUZDV-in0",
    sourceType: "lyric_video",
    lyricsSnippets: ["A quiet young love is written into a memory under the trees."],
  },
  {
    id: "rap-see-you-again",
    name: "See You Again",
    artists: "Wiz Khalifa, Charlie Puth",
    genre: "rap",
    videoId: "xl8thVrlvjI",
    sourceType: "official_audio",
    lyricsSnippets: ["A goodbye becomes a promise to meet beyond the road."],
  },
  {
    id: "rap-gods-plan",
    name: "God's Plan",
    artists: "Drake",
    genre: "rap",
    videoId: "xpVfcZ0ZcFM",
    sourceType: "music_video",
    lyricsSnippets: ["Success, pressure, and gratitude move through a calm flex."],
  },
  {
    id: "rap-sicko-mode",
    name: "SICKO MODE",
    artists: "Travis Scott",
    genre: "rap",
    videoId: "d-JBBNg8YKs",
    sourceType: "official_audio",
    lyricsSnippets: ["A beat switch turns a night ride into a stadium rush."],
  },
  {
    id: "rap-bigcityboi",
    name: "Bigcityboi",
    artists: "Binz",
    genre: "rap",
    videoId: "jgZkrA8E5do",
    sourceType: "music_video",
    lyricsSnippets: ["A confident city character walks through nightlife with style."],
  },
  {
    id: "rap-bai-nay-chill-phet",
    name: "Bai Nay Chill Phet",
    artists: "Den, MIN",
    genre: "rap",
    videoId: "xEXyWsgk9EY",
    sourceType: "official_audio",
    lyricsSnippets: ["Work pressure fades into a relaxed ride with someone warm nearby."],
  },
  {
    id: "rap-exs-hate-me",
    name: "Ex's Hate Me",
    artists: "B Ray, Masew, AMEE",
    genre: "rap",
    videoId: "ff7dvE-4mMA",
    sourceType: "lyric_video",
    lyricsSnippets: ["A broken relationship becomes sharp, catchy, and hard to ignore."],
  },
]
