import type { TrackAudioSourceType, TrackGenre } from "@/lib/tracks"

export interface CuratedSongSeed {
  id: string
  name: string
  artists: string
  genre: TrackGenre
  videoId: string
  sourceType: TrackAudioSourceType
  lyricsSnippets: string[]
}

export const CURATED_SONG_SEEDS: CuratedSongSeed[] = [
  {
    id: "usuk-blinding-lights",
    name: "Blinding Lights",
    artists: "The Weeknd",
    genre: "usuk",
    videoId: "fHI8X4OXluQ",
    sourceType: "official_audio",
    lyricsSnippets: ["I said, ooh, I'm blinded by the lights, No, I can't sleep until I feel your touch"],
  },
  {
    id: "usuk-shape-of-you",
    name: "Shape of You",
    artists: "Ed Sheeran",
    genre: "usuk",
    videoId: "JGwWNGJdvx8",
    sourceType: "music_video",
    lyricsSnippets: ["The club isn't the best place to find a lover, So the bar is where I go"],
  },
  {
    id: "usuk-hello",
    name: "Hello",
    artists: "Adele",
    genre: "usuk",
    videoId: "T1tl66trXTQ",
    sourceType: "official_audio",
    lyricsSnippets: ["Hello from the other side, I must've called a thousand times"],
  },
  {
    id: "usuk-bad-guy",
    name: "bad guy",
    artists: "Billie Eilish",
    genre: "usuk",
    videoId: "4-TbQnONe_w",
    sourceType: "lyric_video",
    lyricsSnippets: ["So you're a tough guy, Like it really rough guy, Just can't get enough guy"],
  },
  {
    id: "usuk-blank-space",
    name: "Blank Space",
    artists: "Taylor Swift",
    genre: "usuk",
    videoId: "e-ORhEE9VVg",
    sourceType: "music_video",
    lyricsSnippets: ["Got a long list of ex-lovers, They'll tell you I'm insane, But I've got a blank space, baby, And I'll write your name"],
  },
  {
    id: "usuk-levitating",
    name: "Levitating",
    artists: "Dua Lipa",
    genre: "usuk",
    videoId: "WHuBW3qKm9g",
    sourceType: "lyric_video",
    lyricsSnippets: ["If you wanna run away with me, I know a galaxy And I can take you for a ride"],
  },
  {
    id: "usuk-as-it-was",
    name: "As It Was",
    artists: "Harry Styles",
    genre: "usuk",
    videoId: "V1Z586zoeeE",
    sourceType: "official_audio",
    lyricsSnippets: ["In this world, it's just us, You know it's not the same as it was"],
  },
  {
    id: "usuk-uptown-funk",
    name: "Uptown Funk",
    artists: "Mark Ronson, Bruno Mars",
    genre: "usuk",
    videoId: "7Ya2U8XN_Zw",
    sourceType: "official_audio",
    lyricsSnippets: ["Girls hit your hallelujah (whuoo), 'Cause uptown funk gon' give it to you"],
  },
  {
    id: "usuk-believer",
    name: "Believer",
    artists: "Imagine Dragons",
    genre: "usuk",
    videoId: "IhP3J0j9JmY",
    sourceType: "official_audio",
    lyricsSnippets: ["Pain! You made me a, you made me a believer, believer"],
  },
  {
    id: "usuk-roar",
    name: "Roar",
    artists: "Katy Perry",
    genre: "usuk",
    videoId: "mwL1cohnHNE",
    sourceType: "lyric_video",
    lyricsSnippets: ["I got the eye of the tiger, a fighter, dancing through the fire, 'Cause I am a champion and you're gonna hear me roar"],
  },
  {
    id: "usuk-someone-like-you",
    name: "Someone Like You",
    artists: "Adele",
    genre: "usuk",
    videoId: "22c3_LoIfZQ",
    sourceType: "official_audio",
    lyricsSnippets: ["Never mind, I'll find someone like you, I wish nothing but the best for you, too"],
  },
  {
    id: "usuk-sunflower",
    name: "Sunflower",
    artists: "Post Malone, Swae Lee",
    genre: "usuk",
    videoId: "ApXoWvfEYVU",
    sourceType: "music_video",
    lyricsSnippets: ["Then you're left in the dust, unless I stuck by ya, You're the sunflower, I think your love would be too much"],
  },
  {
    id: "vpop-hay-trao-cho-anh",
    name: "Hay Trao Cho Anh",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "G8IlfFMt3so",
    sourceType: "lyric_video",
    lyricsSnippets: ["Hãy trao cho anh, hãy trao cho anh thứ tình yêu mà anh đang mong chờ"],
  },
  {
    id: "vpop-see-tinh",
    name: "See Tinh",
    artists: "Hoang Thuy Linh",
    genre: "vpop",
    videoId: "UfMEtjxzpBk",
    sourceType: "official_audio",
    lyricsSnippets: ["Giây phút em gặp anh là em biết em see tình, Tình tình tình tang tang tính tang tình tình tình tang tang tang"],
  },
  {
    id: "vpop-nang-tho",
    name: "Nang Tho",
    artists: "Hoang Dung",
    genre: "vpop",
    videoId: "0SJAzTGh1SE",
    sourceType: "official_audio",
    lyricsSnippets: ["Ta gặp nhau giữa ngày buồn bã, vì anh vội vã chắp tay... Thôi thì anh xin làm chàng thi sĩ, dệt vần thơ tặng em"],
  },
  {
    id: "vpop-co-chac-yeu-la-day",
    name: "Co Chac Yeu La Day",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "6t-MjBazs3o",
    sourceType: "music_video",
    lyricsSnippets: ["Có chắc yêu là đây, đây, đây, đây, đây, Chắc yêu là đây, đây, đây, đây, đây"],
  },
  {
    id: "vpop-buoc-qua-nhau",
    name: "Buoc Qua Nhau",
    artists: "Vu",
    genre: "vpop",
    videoId: "ixdSsW5n2rI",
    sourceType: "music_video",
    lyricsSnippets: ["Một chiều thu man mác hơi sương... Và mình bước qua đời nhau, để làm nhau đau"],
  },
  {
    id: "vpop-de-vuong",
    name: "De Vuong",
    artists: "Dinh Dung",
    genre: "vpop",
    videoId: "qkPgUgkQE4Y",
    sourceType: "music_video",
    lyricsSnippets: ["Một bậc quân vương mang trong con tim hình hài đất nước, Ngỡ như dân an ta sẽ chẳng bao giờ buồn"],
  },
  {
    id: "vpop-noi-nay-co-anh",
    name: "Noi Nay Co Anh",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "FN7ALfpGxiI",
    sourceType: "music_video",
    lyricsSnippets: ["Cầm tay anh, dựa vai anh, kề bên anh nơi này có anh"],
  },
  {
    id: "vpop-lac-troi",
    name: "Lac Troi",
    artists: "Son Tung M-TP",
    genre: "vpop",
    videoId: "WQU8avEv6CQ",
    sourceType: "lyric_video",
    lyricsSnippets: ["Người theo hương hoa mây mù giăng lối, Làn sương khói phôi phai đưa bước ai xa rồi"],
  },
  {
    id: "vpop-co-em-cho",
    name: "Co Em Cho",
    artists: "MIN, Mr A",
    genre: "vpop",
    videoId: "PqS2YDItY3Y",
    sourceType: "lyric_video",
    lyricsSnippets: ["Người đàn ông em yêu đôi khi có những phút giây yếu đuối... Ngoài kia nếu có khó khăn quá về nhà anh nhé, có em chờ"],
  },
  {
    id: "vpop-sau-tat-ca",
    name: "Sau Tat Ca",
    artists: "ERIK",
    genre: "vpop",
    videoId: "XaXiLdlgMo0",
    sourceType: "official_audio",
    lyricsSnippets: ["Sau tất cả mình lại trở về với nhau, Tựa như chưa bắt đầu, tựa như ta vừa mới quen"],
  },
  {
    id: "vpop-anh-nha-o-dau-the",
    name: "Anh Nha O Dau The",
    artists: "AMEE, B Ray",
    genre: "vpop",
    videoId: "aMW2Yf7PxM4",
    sourceType: "official_audio",
    lyricsSnippets: ["Anh nhà ở đâu thế, Cứ tới lui trong tim tôi chẳng nhớ đường về à"],
  },
  {
    id: "vpop-co-chang-trai-viet-len-cay",
    name: "Co Chang Trai Viet Len Cay",
    artists: "Phan Manh Quynh",
    genre: "vpop",
    videoId: "EUEUZDV-in0",
    sourceType: "lyric_video",
    lyricsSnippets: ["Có chàng trai viết lên cây, lời yêu thương cô gái ấy, Mối tình như gió như mây, nhiều năm trôi qua vẫn thấy"],
  },
  {
    id: "rap-see-you-again",
    name: "See You Again",
    artists: "Wiz Khalifa, Charlie Puth",
    genre: "rap",
    videoId: "xl8thVrlvjI",
    sourceType: "official_audio",
    lyricsSnippets: ["It's been a long day without you, my friend, And I'll tell you all about it when I see you again"],
  },
  {
    id: "rap-gods-plan",
    name: "God's Plan",
    artists: "Drake",
    genre: "rap",
    videoId: "xpVfcZ0ZcFM",
    sourceType: "music_video",
    lyricsSnippets: ["God's plan, God's plan, I hold back, sometimes I won't, yuh"],
  },
  {
    id: "rap-sicko-mode",
    name: "SICKO MODE",
    artists: "Travis Scott",
    genre: "rap",
    videoId: "d-JBBNg8YKs",
    sourceType: "official_audio",
    lyricsSnippets: ["Out in nature, late in the night, Sun is down, freezin' cold, That's how we already know winter's here"],
  },
  {
    id: "rap-bigcityboi",
    name: "Bigcityboi",
    artists: "Binz",
    genre: "rap",
    videoId: "jgZkrA8E5do",
    sourceType: "music_video",
    lyricsSnippets: ["Nghiện thuốc có thể Lào Cai, Nhưng nghiện em không thể nào cai"],
  },
  {
    id: "rap-bai-nay-chill-phet",
    name: "Bai Nay Chill Phet",
    artists: "Den, MIN",
    genre: "rap",
    videoId: "xEXyWsgk9EY",
    sourceType: "official_audio",
    lyricsSnippets: ["Đêm nay vi vu đôi ba dặm đường, em ơi có khi ta chẳng cần giường... Bài này chill phết"],
  },
  {
    id: "rap-exs-hate-me",
    name: "Ex's Hate Me",
    artists: "B Ray, Masew, AMEE",
    genre: "rap",
    videoId: "ff7dvE-4mMA",
    sourceType: "lyric_video",
    lyricsSnippets: ["Tất cả người yêu cũ đều ghét anh, Không một ai trong số họ muốn làm bạn"],
  },
]
